### ISSUE TITLE
Revised Hint Interaction (not priority)

### ISSUE THREAD

**Issue by tmuray** [marshall62/mathspring#145]
This issue keeps coming up so we should keep it on the stack for fixing:
- various types of confusions arise in playing and replaying the hints: e.g. only being able to replay the last one you saw, and if you missed one you can' figure out how to see it again.  These would be solved by a modification like the following:
- The Hint interaction box (1) shows how many hints are available and which have been played.  (2) you can replay any hint by clicking on that item in the hint interaction box.  (3) of course, the button to play a hint is disabled until after you have played the hint before it.

**Comment by marshall62** [comment]
I agree that it would be nice to have some better display of this and better control over it for the student.   I'm finding that Flash problems (the majority of the system at this point) behave inconsistently.   Some respond to the replay-hint button and replay the last hint shown.   Some don't.  
So its clear to me that getting Flash to move from one hint to another (particularly backwards) is not reliable.    HTML problems are much more reliable in this regard.

So what I built that will work for all the problem types we have is a slight improvement.   When the problem loads it changes the Hint button so that it displays the number of hints available like:
Hint (3)

When you click the button to ask for a hint it then changes to something like:

Hint (1/3)  
to show that we are looking at the first hint of three.

I know this doesn't really address being able to go back but it would take a lot more work to build a set of controls on screen so that the user could select some prior hint to go to.   Then after doing all this work,  it may well be the case that Flash won't go there reliably and now we've got a buggy new feature.    With HTML problems, I don't think we'd have this problem but it still requires a different button than "replay hint" to allow the user to select which previous hint they'd like to see because the replay-hint button implicitly only replays the current hint.   With problems built with quickAuth, the hints do minimize so that the user can move back and forth any way they like.  

So all these different formats and their quirks are part of why there is confusion.   About the best that could be done would be to display a set of controls for HTML problems that are not quickAuth but I just don't think having an interface that is changing all the time with no rhyme or reason (from the users perspective) is a good thing.
