### ISSUE TITLE
***Bug: Topic switch does not respect "content failure threshold" parameter

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#166]
Students are leaving out of a topic for "I cannot find an easier problem for you" too fast, after two failures to find something easier. It is not respecting the parameter "content failure threshold" that I had set in the class, which was actually 8 instead of 2. In this case, I entered the topic for a second time (note running counts should  be reset every time you re-enter a topic); after two incorrect problems, it told me it cannot find any easier problems. Two ( 2 ) was the minimum number of problems in a topic,  8 was the mastery threshold .

The class we have been using, and will use for this study, is called Winter 2015, classid=1060.

Is it picking the default of the pedagogy and not what I had set in the teacher tools? Is it not resetting the counters when you enter the topic again?

--Ivon

**Comment by marshall62** [comment]
We redesigned the ProblemSelector so that it is less prone to failure.   ContentFailure was one of the main problems with the previous design.   The system no longer is tolerant of failures to find easier or harder problems.   Once it cannot find a problem that is easier, it must switch topics rather than selecting harder problems.    So we cannot fulfill this request without building a new problem selector with a different set of requirements
