### ISSUE TITLE
quickAuth:  need math expressions to avoid intermediate vars

### ISSUE THREAD

**Issue by marshall62** [marshall62/mathspring#170]
In the problem $x + $y / $z

I need an intermediate var $q which I have to manually set to $y/$z because I need hints that refer to this computation.   So I really do need to be able to have expressions like $y/$z evaluated and plugged.

**Comment by mfrechet** [comment]
Quick clarification:

Do you need to set a variable $q to "$y/$z" in the problem authoring tool, or do you want to skip $q altogether and just enter "$y/$z" into the hint text and have it evaluated?

At first I assumed you meant the second, but as I was working the first interpretation occurred to me.

**Comment by marshall62** [comment]
I'd like to avoid having to create intermediate variables which is what I
have to do now.   If we could have expressions like $x/$y  in the texts
then this would solve the problem.   I anticipate some difficulties with it
though.  If we had basic arithmetic operators including exponentiation
using x^4  that would be helpful.

**Comment by mfrechet** [comment]
Ok, that is what I first thought.  I'm glad it's what you meant, because I
think I'm nearly done!  It will do as follows:

//Can parse a simple expression containing only numbers and a single
operator from the set {+,-,/,*,^}.  Anything else will fail.  Uses infix
notation.

I have the first stab at it written.  I just have to test it and remove
the bugs.  It should be fairly simple to add other operator, later. 
Adding an expression with multiple operators is more complicated due to
order of operations.

It also currently just fails if given an improperly formatted input,
returning NaN in most cases.  I could probably make it fail softer if we
wanted, but I'd be hard put to make it fail in a way that didn't mess up
the problem in some way unless we had input validation in Tom's tool.

I did it so that enclosing the expression you want evaluated in {} (like
movies or images) should make it get evaluated.

Once I have the bugs worked out of this I'm moving on to the preloading of
audio (and maybe also video?).  I took a stab at it already, and it
certainly doesn't break anything, but I'm unsure how to tell if it is
working or not doing anything at all.  Also, the current solution preloads
all the audio/video components, not just the next one in line, so I should
work on improving that.

Best,
Melissa

**Comment by marshall62** [comment]
So as far as telling if your preloading is working.   Do you use the Chrome
debugger?   You can open the developer tools and go to sources and set
breakpoints in your javascript and then click buttons to run/step.   I
would think you could use this to see if your code is loading data
structures in the ways/times you want.

As far as expressions.   I think we'll need stuff that supports multiple
operators including parens.    So $x*($y+$z^2) is something that we'll want
to support.   I think you'll find that this isn't that hard to do but it
does mean parsing the expression and building a tree and then you evaluate
by walking the tree depth first.   I think if you look up expression
evaluation you'll find a good description of how to do it.   And I bet
there are probably java packages that do the whole thing for you if you
give a string so maybe you plug the values into the variables and then send
the string into an expression evaluator and it gets done for you.

**Comment by mfrechet** [comment]
I have used Chrome debugger, but for some reason it didn't occur to me.  I
guess because the occasion where I need it comes up so rarely.  I'll try
that, thanks.

There is a Java library for evaluation, ScriptEngine, though I will need
to preprocess a few things that it does not evaluate in the way we want. 
I was going to look into it after getting some preliminary functionality
up and tested so you could start using it, but I could just switch now. 
It shouldn't actually be too huge of a change from what I have.  I'll
update you when next I have interesting news on this.

Melissa

**Comment by mfrechet** [comment]
Actually, since we control the source of the input, javascript eval might
do this job nicely, again with some preprocessing of things like
exponents.

**Comment by marshall62** [comment]
Yeah.  I didn't even think of a built in eval method.   I don't need the
expression stuff right away so why don't you try to get it working in a
generalized way so that when it goes in I can test it all the way.

**Comment by mfrechet** [comment]
Ok, sounds good.  The eval method can be less than secure if you don't
trust the information coming into it, but I'm assuming we trust what is in
our database.  If for some reason this is not the case, please let me
know.

**Comment by marshall62** [comment]
Let's trust it.
