### ISSUE TITLE
Problems seeing quick-author content

### ISSUE THREAD

**Issue by tmuray** [marshall62/mathspring#186]
I'm doing some quick-auth testing and running into issues.

1. problem 1361 there are 3 hints (last is answer give-away) but only one shows up in math spring. 

2. The problem audio does not seem to play for quick-auths.  Eg. 1340.  But hint audio seems to work. 

3. Minguie created problem 1364.  For some reason the problem image  Quadrilateral_angles.png is not coming up and I can't figure out what is wrong.  (The hint audio is working so I know the media folder uploaded in git OK).  Can you have a look?

**Comment by marshall62** [comment]
I am seeing that sound does work ( I tested the problem 1348 which has sound  with hints) but am seeing that the quickAuth engine doesn't seem to be configured correctly.  Forwarded this to Melissa.

**Comment by marshall62** [comment]
I checked 1364.  Audio for problem and hints works.  It doesn't show the last hint (third one) because it is marked as givesAnswer=1.

I am totally confused about hints with givesAnswer=1 .    Different people have asked for different things.    The last I recall Ivon asked for hints that have givesAnswer=1 not to show up.   But other people continue to question why hints don't show up.   There also may be a different expectation if a problem is playing as an example (i.e. that it show hints marked with givesAnswer=1).    When givesAnswer=1 was put into use it was on hints that said something like "Choose Answer D" and it made sense not to show these kinds of hints anymore to help prevent thoughtless click-throughs.  
But then people (Lynn) started building meaningful hints (such as alternate solutions) into hints that were marked with givesAnswer=1 and now she wants them to show up (or us to add another button to the GUI that is "Show Answer").    We have to get people singing from one songsheet on this.

**Comment by tmuray** [comment]
Dave, I am getting these github messages...

**Comment by marshall62** [comment]
OK.   Thanks
