### ISSUE TITLE
Eventlog Detail of Characters' Messages

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#193]
Hi David and Melissa,

Since Wixon started visualizing event logs we have come to be worried about what is being logged in the EventLog over past data. We really need to know details about the intervention, what kind of stuff happened. If the SPP was offered, there should be an "SPP offered" or alike somewhere so that we can recreate what happened. Also, the same thing and maybe more level of detail for the within-problem interventions. Even a comment in "activityName" or alike would be enough.

Now Sarah is looking at how students responded to character messages (how do they behave after a character says something specific?), by  looking at the Eventlog, and I am wondering: have we even recorded in the past which messages each character said, whenever they talked?

There was a characters study last spring that I know we had to discard data for as the timers were wrong, remember? That was Spring 2014 (June). But since then we have run other studies, and we can use that data to see how students have responded to a variety of character messages (as it appears that the FullEmpathy condition yielded better posttests, at least in interest, motivation, etc.).  

Last, can you remind me of what was the issue with the timers that we had 1 year ago? Since when to when were they broken? Do you know if it affected the Eventlog Table only or the studentproblemhistory table also?  I am trying to see if we can "rescue" any of that past data at all, and make sure that we don't retrieve the wrong data thinking that it is fine.

--Ivon

**Comment by marshall62** [comment]
When an intervention tries to send the student to the MPP we have a ShowIntervention event that has  edu.umass.ckc.wo.tutor.intervSel2.MyProgressNavigationAskIS  in the activityName column.
I found one case in which we were not storing the name of the intervention correctly (it was saying "0" when the intervention was a HighlightHint).   The bug is because we were relying on something in the student state to identify the last intervention given.   I've changed how we get the names of the interventions to put in this field of the eventlog so that values will be simpler (e.g.  it will now be 
ShowMPPButton instead of the above).   I'm not sure what other information you want along with that.  Do you mean that if the intervention is asking about the Emotion INTEREST, that somewhere in the eventlog entry it should save both the name of the intervention ( AskEmotion) and somewhere else it should save parameters that are specific to that instantiation of the intervention?

We do record the movie clip name (which is what identifies the learning companion's action).  For example, do the query:
select emotion from eventlog where action="NextProblem"
Is there a particular place that you are expecting it and not seeing it?

**Comment by IvonArroyo** [comment]
David,

I think this is close to settled. You will find a place to put this file,
as you will continuously edit it, as any change to the DB logging, DB
structure, table names, fields, etc. is changed.

Also, whenever what you write on the DB changes in event log,
studentproblemhistory, etc.  chronologically. You could organize it per
year, or per table per year, whatever you want. You will be the "owner" of
this file, while I could still edit as I discover new stuff. It could live
with the code, github, google docs, whatever you prefer.

Start from today, and the DB in its current state, and start thinking back
in time when the logging of problems, interventions, timestapms, or
anything changed. Even if you can say "approximately in  2013 such and such
changed", it is helpful.

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

**Comment by marshall62** [comment]
eventlog is saving information about interventions given and a google document that keeps track of the db changes is maintained.
