### ISSUE TITLE
Cleaning up list of reports page

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#211]
Hi David,

There are many reports that don't work any more.

Until those get fixed, we should remove them, as it is confusing to see broken reports.

The following links should be removed from the list of reports:

Pre/Posttest problem summaries per class	Individual problems in the pre/posttest reported on the class
Pre/Posttest problem detail per student  Shows individual pre/post test problem scoring data per student

An alternative to completely removing them is to move them down towards the bottom, under another section, such as "Reports that are coming" or alike.

User names and passwords should be moved to the top.

--Ivon

**Comment by marshall62** [comment]
Yes.  It is unfortunate.  I'm having CSCF look into putting a different
Java on rose and this might allow us to see the reports that rely on
Jcharts.   There are also some bugs that I've found and am trying to fix.

 Some reports were built in the past that relied on pulling data out of
woproperties table.   This table got too big and we had to use more
efficient methods for storing data about students which meant that some
reports couldn't work anymore.   Maybe those have already been removed from
the list since I don't see reports breaking.   I'll remove the pre/post
test reports which don't make sense since we don't administer pre and post
tests.

**Comment by marshall62** [comment]
I removed the pre/post reports and moved the roster up.   I also made the reports pages look like the rest of the teacher tools (using Mathspring name rather than Wayang Outpost).  It's now much better.

We'll have to identify the reports that no longer work and either fix or remove them.  I am awaiting CSCF installing Java 8 on rose so that I can determine if JCharts will be available or not.
