### ISSUE TITLE
Can't set up pedagogies for the class from teacher tools

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#224]
Hi David,

With these new limited teacher tools I could not manage to set pedagogies for the class from the Teacher Tools, I had to modify the classpedagogies  table.

Is it expected that this would work this way, or am I missing something? Am I supposed to see all pedagogies as an "administrator teacher"?

--Ivon

**Comment by marshall62** [comment]
Yes.  When you are logged in as a teacher, you do not have the ability to
select from all the pedagogies because the list is too long and confusing.

The solution is to login with your admin user/password.  Then select the
teacher and class that you want to work with .  Click on the pedagogies
button then select "advanced".  This will allow you to select from the long
list.   So the idea is that only admins should be setting up classes in
this advanced manner.

**Comment by IvonArroyo** [comment]
Cool, thanks!

The teacher tools are really looking good and powerful.

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute
