### ISSUE TITLE
BUG: Report summary per problem 

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#256]
Hi David,
There is a pretty nasty bug in the most useful teacher report, that is skewing the data. 
The report should exclude problems that have been shown as example (demo) problems. It should only include practice problems.
Can you fix this really soon? It is a small glitch that can be fixed by tweaking the SQL query.
http://rose.cs.umass.edu/woj/WoAdmin?action=AdminViewReport&teacherId=76&classId=1220&reportId=4&state=showReport

Fixing issues with these reports is becoming more important so that teachers can find the system valuable. For instance, the other issue I reported some time ago about "report per skill" turning into a "per Common Core Standards report" is important too.

**Comment by marshall62** [comment]
I'll look into it today.

**Comment by marshall62** [comment]
I fixed the bug in the report.  It should no longer count problems that
were shown as demos or examples.   This was a little more complicated than
I first thought and I'm not sure how you detected that this was a problem
in the report because I think it was probably a subtle difference between
numbers including examples and numbers that don't.   So hopefully, it is
now what you want.

Regarding the report that shows per skill vs common core standards:   Early
this fall both Bev and Shamya were insistent that I give Shamya a task to
work on.  So we all agreed this would be an ideal task for her to do.   In
late October when I was checking on her status with it,  she told me that
her class in machine learning was now consuming her time and that she was
focused on a different project and that she would have the report done by
November 5 or so.  I haven't heard from her since and don't really expect
that she's working on it.   I'll send Shamya an email to see if she is
planning to do work for us and to complete this task.
