### ISSUE TITLE
Demo with DODEA scheduled for Dec.16th

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#260]
Hi David, 

We are scheduling right now a meeting to give a MathSpring demo to the military school people. If this goes well, it could be a hit for MathSpring to be used in many schools, and money in the future.

Before Dec. 16th, could we get the following things fixed:

- Login screen
- Report per skill based on common core instead of our skills (exclude example problems)
- REmove Tom's mastery line from the progress trajectories of mastery, just one line.

--Ivon

**Comment by marshall62** [comment]
We can do this but we will need to release other fixes along with this including the pedagogy changed that I mentioned in another email.   It is difficult to make releases that include only some bug fixes but not others because we are then in a position where the developers code does not match what is released.     So we need to make a release soon that gets tested,  This will include all the fixes you are requesting too.

**Comment by IvonArroyo** [comment]
Sure, that is fine, as long as it is tested to some extent.

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

**Comment by IvonArroyo** [comment]
Thank you for these changes, it really made a difference during the demo.

**Comment by marshall62** [comment]
I'm glad the demo to DODEA went well.  I'm not sure we can assume the
collaboration system is functioning really well though.

As I'm sure you're aware the collab system has some complexity and Melissa
made some changes a few weeks back so that the event names would be better
but also some programming changes that altered how it behaved (which was
also a request).  This latter change seems to have brought in a bunch of
bugs which all manifest as the problem selector generating
index-out-of-range errors or similar issues.  Those kinds of errors
indicated to me that Melissa's collab code was not correctly updating the
student state which then causes the problem selector to fail.    I pointed
her in this direction but never had a sense that she really pursued it or
did anything about it.   So I expect there are still going to be those
kinds of bugs showing up every now and then.  It tends to happen AFTER a
collaboration ends.

Bev is going to meet with Melissa about the issue of her not being
productive.  This has been a problem for some time and I think we are going
to have stop paying Melissa as a programmer.  This will mean that we'll
hire someone else (I'm hoping it will be Rafael) and he will likely have to
learn how quickAuth and collaboration work so that he can reliably
maintaining those systems and do some other things as well.  Once Bev
speaks to her,  I'm expecting that Melissa will respond by putting in some
more effort even though we won't be continuing the appointment starting in
mid Jan.  So testing collaboration thoroughly and helping her identify what
causes these bugs might be something we put on our agenda in the next
several weeks.

**Comment by IvonArroyo** [comment]
Hi David,

OK, thanks for clarifying. Though Melissa in general had done a good job I
thought regarding the collaboration, but that is what I see from outside
only.

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

**Comment by marshall62** [comment]
This is why I was a little slower to say something.  We really needed her
contribution to that system once she wrote it.   Because I am often bogged
down with other problems I've needed her taking responsibility for it.
Unfortunately, she doesn't really seem to do work unless you constantly
press her about it.  I've been trying to do that this fall, but haven't
been finding it to be effective especially if meetings get canceled or if
she doesn't come.

**Comment by mfrechet** [comment]
Hello,

    It is true that I have fallen behind in my work, and for that I
apologize.  I had a few bad weeks during the end of the summer and the
very beginning of the semester and have yet to make up all of the time
that I lost, though I do plan to.  I don't believe it is to the extent
that David seems to think, however, as I am only employed for 15hrs a
week, which is less than two full work days per week, and this has
been the case since the end of last Spring, which I'm not sure he was
aware of.
    I will be pressing to get more done in the coming weeks, because I
will not be working a paid position with the group after this January.
 Unfortunately due to circumstances that are not under the control of
myself or anyone in the group, a RA position can no longer meet my
financial needs, so I have had to find work elsewhere starting next
semester.  I informed Beverly of this over a month ago.  I did not
bring it up in a group meeting because I assumed Beverly was waiting
until she hired someone else to tell people.  I want to make sure I
tie up as many loose ends as possible before going to a new job,
though I will still be around in an academic capacity and so can still
put in some time to work on bugs even after I no longer have a paid
position.

    David, I am making quite a bit of progress in solving these bugs.  I
have solved several of them already.  I have not committed these
solutions because they seem tied together in ways I'm not sure I've
fully identified and I was hoping to be able to check how they
interact before committing, which I can only do once all the known
bugs are solved.  It seemed more valuable to me to focus on fixes and
their interactions until we had another test scheduled, at which point
I would commit the best of what I have before the test.  If you would
prefer, however, I can make a commit with the fixes I have now.

Melissa
