### ISSUE TITLE
Fix per topic report (the one with cells that are red, blue, green, yellow)

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#264]
After talking with some teachers, training, etc. the realization is that this report needs to have less color, it is too much information to process, many of which is not relevant.

Make cells WHITE when they have not enough problems seen, that means when less than 10 math problems have been solved.  Cells should be painted according to the color criteria only when students have solved at least 10 math problems in the topic.

Make sure the denominator corresponds to SOLVED problems, and not just skipped problems.

**Comment by marshall62** [comment]
Changed report so that it only color-codes topics where student has seen 10 problems or more.  I verified that what is shown in each cell is:

# problems SOLVED / # problems SEEN

Problems SEEN includes only practice problems.  They are either solved (answered correctly), skipped (never answered), or incorrect (answered but never correctly).     Because many students click on on answers until one is correct, the SOLVED number may not mean very much especially because the mastery calculation factors in a lot more than whether a student finally answers a problem correctly.  This could result in a low mastery but a fraction where problems SOLVED is nearly the same as problems SEEN

**Comment by IvonArroyo** [comment]
Right, that is not correct. It should be :

solved on first attempt  /  problems solved

Can you fix this?

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

**Comment by marshall62** [comment]
OK.  It's now using solved-on-first / solved.   I think those are much more useful numbers.
It's interesting how high the mastery numbers are even when students don't solve many on the first attempt.
