### ISSUE TITLE
Bug in Pedagogies: Asking for frustration and interest, and timing

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#266]
Hi David,

Let's please fix these pedagogies ASAP, so that the 4 pedagogies we used for the study (collaboration and individual mode) ask frustration and interest (instead of frustration and confidence).

Also, any way that collaboration can show up every X amount of time, instead of every X amount of problems?

Last, how does the system juggle interventions? If it has to choose collaboration vs. asking about an emotion, both interventions, how does it prioritize one vs. another? There were less emotion requests in the collaboration condition than in the individual condition and we don't want that to happen, we want similar amount of emotion questions in both.

--Ivon

**Comment by marshall62** [comment]
The 4 pedagogies are using frustration and interest.

Collaboration was running with 80% probability after a 5 minute wait since last collab

Interventions are sorted into priority order.   The AskEmotion intervention takes priority over the Collab intervention so my best guess is that the time spent waiting for a partner and being in a collab are why users are not seeing as many AskEmotion interventions

**Comment by marshall62** [comment]
I've spent a lot of time looking into why these students were seeing questions about confidence.  I can't find any bug in the code and am pretty convinced that the pedagogies were configured to ask about frustration and interest.   There were bugs in the code prior to 12/15/15 that were making logging interventions unreliable so the best we can do is test this again with students and verify that emotions are being asked in the correct frequency and that the correct emotions are asked about and logged.
