### ISSUE TITLE
ASAP for JULY study:  New Emotion Question intervention 

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#285]
A new emotion request intervention that has an "open style" form.  We just need to save data for these questions, and compare them later to the other ways in which we ask how they feel. We need to PILOT these with GIRLS INC.

![new mathspring prompt](https://cloud.githubusercontent.com/assets/5631787/15369458/ad0c9434-1d00-11e6-983a-7a9a849df009.jpg)

**Comment by marshall62** [comment]
Done.   The dialog has to scroll to see the 3rd question and input area because of the amount of text.

This form of emotion querying comes up just like the other versions - every N problems or every M minutes which is configured in the database pedagogy table under the _definition_ field where XML configures the AskEmotionIS pedagogy.   You need some config XML like:  

 <interventionSelector onEvent="NextProblem" weight="1" class="AskEmotionIS">
      <config>
        <inputType>freeAnswer</inputType>
        
        <interruptIntervalMin>5</interruptIntervalMin>
        <interruptIntervalProblems>8</interruptIntervalProblems>
      </config>
    </interventionSelector>
