### ISSUE TITLE
Bug: Topic Selection

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#295]
This is for Rafael.
These numbers don't seem to add up, see image:

<img width="650" alt="screen shot 2016-11-15 at 9 52 06 am" src="https://cloud.githubusercontent.com/assets/5631787/20310283/55f673d4-ab19-11e6-8891-aeef5edb8ab7.png">
.
ClassId=1277

Also, could you please change "Total Problems" to "Total problems within desired range". Note that the user might change the problems as they get into the topic --how to deal with this.

--Ivon

**Comment by rezecib** [comment]
Looks like the problem is that the original problem counts were wrong. I checked several cases where they didn't add up, and the sum of the problems by grade level was how many problems were enabled. Looking at the code, it seems that the list of inactive problems sometimes has extra problem IDs in it, and the way it was calculating the total was just (num problems) - (num inactive problems). Maybe @marshall62  would know more about why this happens? Meanwhile I'll change the total to just use the counts calculated by grade.

As for changing it to "Total problems within the desired range", that's very long, so it blows up the table. How about "Total Active Problems"? Considering that they can individually enable/disable problems, I think it's a more accurate description, too.

**Comment by marshall62** [comment]
Not up on this.   What is the part of the code you are talking about that
counts the number of problems in a topic by grade?   If there is "total"
column why is it not just the sum of what is in the various grade columns
for the given topic?   This would be better than some other query that
isn't guaranteed to produce a number consistent with what the columns are
summing to wouldn't it?

On Tue, Nov 15, 2016 at 1:58 PM, Rafael Lizarralde <notifications@github.com

**Comment by rezecib** [comment]
The total was the number that was being displayed before. It's calculated when TopicsEditorHandler.handleEvent calls DbProblem.setTopicNumProbsForClass, which is what did (num problems) - (num inactive problems) (-- as acquired by ProblemMgr.getWorkingProblems and DbProblem.getClassOmittedTopicProblemIds).

Locally I have tentatively changed it to just summing the columns, but I wanted to check that there wasn't some nuance there that I was missing (also, it seems like a minor bug that those extra problem ids are in the omitted problems).
