### ISSUE TITLE
BIG BUG in LOGS: No record of many character emotions in eventlog

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#302]
Hi David,

Unless they are recorded somewhere else, I cannot see any record of several of the 'emotions' (the character messages spoken) in the eventlog.

It is only saving (under 'emotion') the character reaction to a click (incorrect, correct, etc.), but I don't see any of the messages that show up at the beginning of a problem. They should be displayed with the "New problem" row (which is also missing, is this the reason?).

For instance, the characters are talking right now at the beginning of a 'demo' problem also, and there is no record of anything in those problems.

It is important that we have a record of what the characters said, at all times. I believe it is only at the beginning of a problem that the recording is missing.
----

Example: user  nov181 / t  (36574)

Demo problem:  "...Brain grows....? that is so cool"   --> not recorded
practice problem  1133  "Did you know that...."  at beginning of problem --> not recorded
practice problem  1133  Anwer=E (correct)  "You got it!"  --> yes recorded

**Comment by marshall62** [comment]
This was a bug.  Almost all the events coming into the tutor were not having an emotion put into the eventlog.  This is because we were logging the event BEFORE asking the companion if it had something to say.   And the new rule-based companion is now making a lot of statements in an event that never had learning companion actions (BeginProblemEvent)  so substantial changes were made to code to have the logging in place for all events and a new release was made to both WOJ and MS.   

Testing should be done and the eventlog should be scrutinized.
