### ISSUE TITLE
BUG: QuickAuth problems do not play as examples

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#311]
David, is is possible that QuickAuthor problems don't play as examples? 

This is an important issue, as problems may be automatically chosen as examples.  There are new problems created that way, as I have said that whenever possible we should create short answer problems. For instance, all these are marked ready:

1367	5NFA1_2
1372	6RPA2_2
1373	6RPA1_1
1374	6RPA1_2
1375	6RPA1_3
1388	6RPA2_4

In this case, there are some ratios problems that were created with quickauthor, and it chooses the most resembling example.

See screenshot attached
<img width="1042" alt="screen shot 2017-01-05 at 12 29 56 pm" src="https://cloud.githubusercontent.com/assets/5631787/21690585/eb5d19f4-d342-11e6-83a5-e0f9b556cd78.png">

**Comment by marshall62** [comment]
QuickAuth problems do not play as examples is a problem that we kind of
knew about.  I had to go into that system a while ago and rework it
substantially because we couldn't even look at the problems
in the teacher tools if we wanted to see them.  I came up with something
but it wasn't able to really "play" the problem.   So I think this may be a
big project because
the whole quickAuth system was coded in a way that assumed it was playing
inside an iframe that has an immediate parent that is the tutor frame
containing hint buttons and javascript that it can talk to.
I can look into this but I think it's not going to come out without a major
reworking of things in quickAuth and then question is might there be
something that is a better solution to this problem?

I've never thought the whole random selection of an example was a great
idea because it can easily select a problem that is dissimilar to others in
the topic
and is atypical.   On subsequent visits to the topic, it will pick
different ones but it always just trying to find an unseen problem that has
middle difficulty.  In small topics, this means
problems get wasted and we can't again show them.  It would be far better
to designate 1 - 3 problems as examples and the selector would choose
them in that order.   This would allow us to be sure that the problem is
truly representative of the topic and similar to what the student is about
to work with.   I suppose if the topic is all quickAuth problems,
then it becomes a problem because we'd have to create an example that is
built in Edge.

In general,  I think we need to take a look at our means of creating and
presenting content.  I think Edge has been replaced and may not be in favor
and quickAuth just seems to be undesirable because it has no animation and
layout problems.
I'd like there to be a free tool that most people can easily learn to use
to create content that is BETTER than our Flash and Edge content otherwise
it just doesn't seem worthwhile to rebuild the whole interface of the tutor
and then have this playing this old outdated multiple-choice Flash content
which is the majority of what students see.    It might be worthwhile to
ask your two students to look into tools we could be using to create high
quality animations that could play in this tutor.

**Comment by IvonArroyo** [comment]
This is my train of thought... Maybe I found a solution by the end.


The worked out examples feature is a very important feature, David, I know
that you don't agree/like the dynamic selection of demo problems, but this
is the way that our tutor "teaches", showing students how a problem of the
same kind is taught, before they start practicing.

There is a lot of research saying that worked out examples are an excellent
way to teach. Full volumes, they even call it the "worked out example
effect", and some people are ONLY studying worked out examples as part of
their career. Read in wikipedia for instance:

https://en.wikipedia.org/wiki/Worked-example_effect

I think this is probably an important factor that helps with learning in
MathSpring.

There are two issues: one is the examples displayed at the beginning of the
topic, the second is the examples that launch upon clicking the "example"
button.

For the second, for the time being, we can set by hand the examples for
problems that are similar to quickAuth, that share these same standards for
the time being so that those examples don't get chosen, but this is not a
solution,  a big issue, as it might break the tutor eventually, we cannot
predict all the cases that will make these problems not choosable.

We have to find a solution.

For the first issue, the beginning of a topic issue, maybe we can hard-code
demo-example problems for topics, if there is such a thing then it will
always play that one demo problem at the beginning  a topic.

BUT This is NOT a great idea though because of the dynamic nature of
problems and how they are assigned to different grades. The content for a
topic VARIES depending on the grade. That is why we SHOULD NOT probably
hardcode demo problems.

One possibility would be to assign to each problem whether it is "demoable"
or not. Then, when a problem is to be chosen as an example/demo, it has to
be "demoable". This might also allow us to get rid of problems that might
have poor hints and are not good to be shown.

A Solution maybe?

--Ivon


-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

**Comment by marshall62** [comment]
quickAuth problems now correctly play as demos and examples
