### ISSUE TITLE
Bug in LOGS: Inconsistency between Eventlog and StudentProblemHistory

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#314]
Hi David, I will start posting the bugs we found in the logs. Here goes the first one:

While the event log shows correct solving on first attempt for this problem 502, the StudentProblemHistory has effort=NULL while it is clear that it should be SOF. Note time to solve is 66323.

I think an initial effort value should be computed and stored at the StudentProblemHisotry (at least temporarily) at the time when the student solves the problem correctly, and not when the problem actually "ends".

Also, I really encourage you to end a problem when the student clicks on the Student Progress Page button. It will solve a lot of problems and save lots of headaches. There is NO reason for the problem to remain live when they are in the SPP. It screws up all the timers, all our estimations of how long a student stays in a problem.

A few bugs regard this problem 502, I suggest you debug with that problem.
<img width="1061" alt="screen shot 2017-01-20 at 12 23 19 pm" src="https://cloud.githubusercontent.com/assets/5631787/22158901/8125883e-df0c-11e6-8b3c-63fcd5876f53.png">

<img width="721" alt="screen shot 2017-01-20 at 12 33 14 pm" src="https://cloud.githubusercontent.com/assets/5631787/22158951/b1f78944-df0c-11e6-99d8-c409e5c980e6.png">

--Ivon

**Comment by marshall62** [comment]
This bug was fixed awhile ago.   I think the user must have using a system that was built before this fix.

Previously we only updated effort when a problem was completed by clicking the next-problem button.   The fix went in some time in the last year and changed it so that effort is updated at certain times while the student is working on the problem including at the moment when they attempt and are correct.  So this problem (which was never completed) would now be marked with an effort of SOF at the time of attempt.
