### ISSUE TITLE
Bugs in LOGS: demo problems and problemID

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#317]
Second, in demo problems, there is now a new activityName called "demo xx" such as demo 87 in this case. I assume that problem ID = 87 is being played as demo?

Why is then problemID set to 504? Note it changed to 504 just for this row.

<img width="892" alt="screen shot 2017-01-20 at 12 50 55 pm" src="https://cloud.githubusercontent.com/assets/5631787/22159524/50c258d6-df0f-11e6-841b-4ea3c67d2d42.png">

**Comment by marshall62** [comment]
Note: your log snapshot is not reflective of the way events are logged at the time of this writing.  This log was generated in April 2016 and some things have changed since that time:

This is probably the most awkward set of events that we have.   A TopicIntro is no longer considered a math problem.  It behaves more like an intervention at the beginning of a topic so we have a ShowIntervention for TopicIntro that is set to a dummy problem ID 899.  When the user clicks the NextProblem button during the intro that event is logged as an InputResponse (because all interventions end with a user response logged in this way) with problemId=899.   THere is then the option of showing a demo problem which is also handled by an intervention selector but then things get really ugly because the demo has to play like a problem but in a dialog.   We send in a BeginProblem event when the dialog goes on screen (this is not in the event log snapshot you sent so it must have been a fix I added after 4/2016).   This BeginProblem event will be labeled with the problemID (87 in this case) and then when the user hits the Close button which ends the demo you see that a NextProblem event comes in also labelled with the problem ID followed by an EndProblem with this ID.     

The problem ID 899 is placed in the id field when we do not have a legit problem to show. which is true through the topic intro and up until the Demo problem begins.  I fixed a small bug in the dialog that shows the demo so that it does not have a close button in the upper right corner which could cause errors.
