### ISSUE TITLE
Bug in LOGS: ProblemID in TopicIntro rows

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#318]
The rows with activityName='TopicIntro' correspond to actual introductions. Introductions are a problem, with an problemname in the 900s (e.g. problem_901), unless I am missing something. Those problem ids are at most 60.

Why is the problemID set for those topic intros in the eventlog = 502?  By now, the problem for the topic should not have been chosen yet.

If anything, it should be NULL, but not the number of a valid problem to solve. 

![Uploading Screen Shot 2017-01-20 at 12.50.55 PM.png…]()

**Comment by marshall62** [comment]
The TopicIntro is NOT a problem.  It is an intervention.    So the problemId shouldn't be important when looking at these rows in the eventlog.   There was some inconsistency in what problemId is getting put there so I tracked it down and made sure that the problemId 899 is always placed in the event for the TopicIntro.   This ID refers to a dummy problem in the database.   Because of foreign key constraints the id must be a valid problem id so that's why its 899 and not -1 or NULL.
