### ISSUE TITLE
ASAP: user creation issue

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#319]
We need to fix this issue before the study at WPI that tests the user interface starts in a few weeks. Those students are going to be asked to create a student user in mathspring to log in.

When somebody creates a new student user, there is a humongous list of classes which makes it almost impossible to find the class that you are supposed to sign up to.

This would make it much easier for the user:

- List classes in descending classid order, so that more recently created classes are at the top.
- List only classes that were created in the past 2 years.

--Ivon

**Comment by IvonArroyo** [comment]
Can you please send the modified code over email so that Huy and Hoang can make the change on their side also? Both versions should look the same for this one aspect.

**Comment by IvonArroyo** [comment]
I mean, there should be a few lines of code to change only.

**Comment by rezecib** [comment]
I'm looking into this. I have to figure out what files generate that page though.

**Comment by rezecib** [comment]
I have this working on my local test server. I am using the createTimestamp column in the class table, but it looks like it wasn't being filled in before last March. Given that that spans most of 2016+2017, is that sufficient?

**Comment by marshall62** [comment]
I'm not seeing any response from Ivon on this.   My guess is that this is sufficient.   If not, she'll have to go in and add timestamps to classes created earlier than March 2016 and use a date that fits within the window of time that you filter into the results.  

I'm not loving this idea of emailing code.   This probably means that their version of the system has not been kept in sync with the master branch and that if they want to have their changes considered for integration into the master, there will be a merge that may be difficult for them if this isn't addressed sooner rather than later.

**Comment by rezecib** [comment]
Agreed. I just pushed the commit and will send a link to the diff and and explanation on why not staying in sync will be problematic.
