### ISSUE TITLE
Bug Fix (within 1 week) please:   

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#320]
There is a bug in Pedagogy "Mini Games (Ask)". We need to use this pedagogy in 2 weeks in a small study in schools with real middle school students in Worcester.

Please test using class 1293 (Rachel's Game Class A)
Teacher: Rachel    Pwd: Burton

These are the bugs I spot here: 

If you Log in with User MiniGames1 or MiniGames4 (password 'Games'), there are 2 external activity games attached to the topic "Fractions Review".  A few different Bugs I found:

1) The game is set up to show after 2 problems, as specified in the pedagogy (I changed the frequency to debug). This happens OK, but, they should show only ONCE. After a n external activity (game) is shown, it should not be offered again (just like a math problem).  If you log out and log back in, something seems to reset and it offers the same game again, for the same topic .

2) There must be an exception because I am getting blank screens for problems, occasionally. Initially I thought it must be a broken problem that doesn't load, but it happened several times for different problem IDs  (as shown in the bottom left of the screen).

**Comment by marshall62** [comment]
External activities were selected in a way that allowed repeating them after logging in again.
I removed this behavior and made is so that a given external activity only plays once for a student and is not offered again.

I'm not certain about part 2 of this.   After external activity plays problems are loading fine.
