### ISSUE TITLE
Classconfig parameters are NOT being respected for topic exit conditions

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#335]
Topics are NOT respecting the parameters set in classconfig for minimums, maximums, mastery level, etc. I think mastery level must be hardcoded somewhere as 0.8 for instance, I changed it to 0.999 and never happened, keeps getting the student out of the topic after 0.8 or so.

I think the maximum number of problems and time also are hardcoded, or maybe defaults are being read?

**Comment by marshall62** [comment]
The values from the lesson definition were being incorrectly overloaded with a default TopicModelParameters object rather than values in the classconfig.  I reworked the overloading process so that if any non-NULL value is in the classConfig table it will be used instead of what is in the lessondefinition's XML.    If NULL value is in the classconfig parameter, then we use what is specified in the lesson definition XML.   To make it easier to set classconfig values (i.e. not using manual db editing) I fixed the teacher tools page that is available to admin users (only).  At the bottom of the Topic Control page you can again use some sliders to set the various items that control topics.   Set them to -1  (or click the OMIT box) to use the value that is in the lesson definition.
