### ISSUE TITLE
Bug in Videos button click

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#348]
I always get a not found page, no matter what:

http://tutor.mathspring.org/ms/267

**Comment by marshall62** [comment]
I see that Tom changed the video field of the problem table in April and didn't let me know.   It now has the id of a row in the Video table.   I fixed this so that we get the link from the Video table now.   This will be available the next  WOJ release but will remain broken in MS until you request a new release.

This is a situation where the shared db does force you to move forward with MS because the database got changed in such a way that MS no longer is compatible with it.
